# Generated by Django 2.2.5 on 2019-09-25 09:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uu_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('facebook_likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uu_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('gross', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('imdb_score', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('aspect_ratio', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('num_voted_users', models.IntegerField(default=0)),
                ('num_user_for_reviews', models.IntegerField(default=0)),
                ('facenumber_in_poster', models.IntegerField(default=0)),
                ('cast_total_facebook_likes', models.IntegerField(default=0)),
                ('movie_facebook_likes', models.IntegerField(default=0)),
                ('num_critic_for_reviews', models.IntegerField(default=0)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('genres', models.CharField(blank=True, max_length=60, null=True)),
                ('movie_title', models.CharField(blank=True, max_length=30, null=True)),
                ('plot_keywords', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('content_rating', models.CharField(blank=True, max_length=30, null=True)),
                ('title_year', models.CharField(blank=True, max_length=30, null=True)),
                ('movie_imdb_link', models.URLField(blank=True, max_length=100, null=True)),
                ('actors', models.ManyToManyField(related_name='movies_as_actor', to='imbdapp.Person')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies_as_director', to='imbdapp.Person')),
            ],
        ),
    ]
