# Generated by Django 2.2.5 on 2019-09-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imbdapp', '0002_auto_20190925_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='gross',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
